import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./components/navbar";
import Footer from "./components/footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Coin Tracer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="bg-[#26272b] text-[#fff]">
      <body className={inter.className}>
        <main className="m-auto max-w-6xl font-rubik">
          <Navbar />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
